name: Build MacSpeechApp

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [ created ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Swift
      uses: swift-actions/setup-swift@v1
      
    - name: Build App
      run: |
        chmod +x build.sh
        ./build.sh
        
    - name: Create Release Asset
      if: github.event_name == 'release'
      run: |
        cd Build
        zip MacSpeechApp.zip MacSpeechApp.dmg
        
    - name: Upload Release Asset
      if: github.event_name == 'release'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: Build/MacSpeechApp.zip
        asset_name: MacSpeechApp-${{ github.event.release.tag_name }}.zip
        asset_content_type: application/zip 